#
# GDC Docs - Config
#

site_name: GDC Docs
site_url: http://gdc-docs.nci.nih.gov
repo_url: https://github.com/NCI-GDC/gdc-docs
copyright: "&copy; 2015-2016"
theme_dir: theme
pages:
- Home: index.md
- API:
  - Getting Started: 'API/Users_Guide/Getting_Started.md'
  - Authentication: 'Commons/Authentication.md'
  - Searching for and Retrieving Data and Metadata: 'API/Users_Guide/Searching_for_and_Retrieving_Data_and_Metadata.md'
  - Downloading Files: 'API/Users_Guide/Downloading_Files.md'
  - BAM Slicing: 'API/Users_Guide/BAM_Slicing.md'
  - Submission: 'API/Users_Guide/Submission.md'
  - Examples: 'API/Users_Guide/Examples.md'
  - Available Fields: 'API/Users_Guide/Appendix_A_Available_Fields.md'
  - Key Terms: 'API/Users_Guide/Appendix_B_Key_Terms.md'
  - Using jsonlint and urldecode for GET to POST Conversion: 'API/Users_Guide/Appendix_C_Using_jsonlint_and_urldecode_for_GET_to_POST_Conversion.md'
  - Release Notes: 'API/Release_Notes/API_Release_Notes.md'
- Data Portal:
  - Getting Started: 'Data_Portal/Users_Guide/Getting_Started.md'
  - About the Data: 'Commons/About_the_Data.md'
  - Authentication: 'Commons/Authentication.md'
  - Features: 'Data_Portal/Users_Guide/Features.md'
  - Projects: 'Data_Portal/Users_Guide/Projects.md'
  - Data: 'Data_Portal/Users_Guide/Data.md'
  - BAM Slicing: 'Data_Portal/Users_Guide/BAM_Slicing.md'
  - Annotations: 'Data_Portal/Users_Guide/Annotations.md'
  - Advanced Search: 'Data_Portal/Users_Guide/Advanced_Search.md'
  - Reports: 'Data_Portal/Users_Guide/Reports.md'
  - Cart and Files Download: 'Data_Portal/Users_Guide/Cart.md'
  - Key Terms: 'Data_Portal/Users_Guide/Key_Terms.md'
  - Release Notes: 'Data_Portal/Release_Notes/Data_Portal_Release_Notes.md'
- Data Submission Portal:
  - Getting Started: 'Data_Submission_Portal/Users_Guide/Getting_Started.md'
  - Submission Workflow: 'Data_Submission_Portal/Users_Guide/Submission_Workflow.md'
  - Authentication: 'Commons/Authentication.md'
  - Overview and Features: 'Data_Submission_Portal/Users_Guide/Features.md'
  - User Access: 'Data_Submission_Portal/Users_Guide/Login.md'
  - Homepage: 'Data_Submission_Portal/Users_Guide/Homepage.md'
  - Dashboard: 'Data_Submission_Portal/Users_Guide/Dashboard.md'
  - Upload and Validate Data: 'Data_Submission_Portal/Users_Guide/Upload_Data.md'
  - Submit and Release Data: 'Data_Submission_Portal/Users_Guide/Submit_Release.md'
  - Browse Data: 'Data_Submission_Portal/Users_Guide/Browse_Data.md'
  - Reports: 'Data_Submission_Portal/Users_Guide/Reports.md'
  - Transactions: 'Data_Submission_Portal/Users_Guide/Transactions.md'
  - Release Notes: 'Data_Submission_Portal/Release_Notes/Data_Submission_Portal_Release_Notes.md'
- Data Transfer Tool:
  - Getting Started: 'Data_Transfer_Tool/Users_Guide/Getting_Started.md'
  - Accessing Built-in Help: 'Data_Transfer_Tool/Users_Guide/Accessing_Built-in_Help.md'
  - Preparing for Data Download and Upload: 'Data_Transfer_Tool/Users_Guide/Preparing_for_Data_Download_and_Upload.md'
  - Data Download and Upload: 'Data_Transfer_Tool/Users_Guide/Data_Download_and_Upload.md'
  - Key Terms: 'Data_Transfer_Tool/Users_Guide/Appendix_A_-_Key_Terms.md'
  - Release Notes: 'Data_Transfer_Tool/Release_Notes/GDC_Data_Transfer_Tool_Release_Notes.md'
- Dictionary:
  - About: 'Dictionary/index.md'
  - Viewer: 'Dictionary/viewer.md'
extra:
  project_root_dir: '/'
  project_org: 'GDC'
  project_description: 'GDC Docs'
  version: 1.0
  dictionary_viewer_page_id: 'Viewer'
  dictionary_app_root: '/apps/dictionary'
markdown_extensions:
  - BSCodeTabExtension:
      default_lang: 'Source'
      show_all_code_as_folders: True
      animate_tab_transitions: False
