copyright: '&copy; 2015-2016'
extra:
  dictionary_app_root: /apps/dictionary
  dictionary_viewer_page_id: Viewer
  encyclopedia_entries_page_title: EncyclopediaEntries
  encyclopedia_page_title: Encyclopedia
  nav_exclude:
  - EncyclopediaEntries
  project_description: GDC Docs
  project_org: GDC
  project_root_dir: /
  version: 1.0
extra_css:
- css/encyclopedia.css
markdown_extensions:
- tables
- BSCodeTabExtension:
    animate_tab_transitions: false
    default_lang: Source
    show_all_code_as_folders: true
pages:
- Home: index.md
- API:
  - Getting Started: API/Users_Guide/Getting_Started.md
  - Search and Retrieval: API/Users_Guide/Search_and_Retrieval.md
  - Downloading Files: API/Users_Guide/Downloading_Files.md
  - BAM Slicing: API/Users_Guide/BAM_Slicing.md
  - Submission: API/Users_Guide/Submission.md
  - System Information: API/Users_Guide/System_Information.md
  - Additional Examples: API/Users_Guide/Additional_Examples.md
  - 'Appendix A: Available Fields': API/Users_Guide/Appendix_A_Available_Fields.md
  - 'Appendix B: Key Terms': API/Users_Guide/Appendix_B_Key_Terms.md
  - 'Appendix C: Format of Submission Queries and Responses': API/Users_Guide/Appendix_C_Format_of_Submission_Requests_and_Responses.md
  - Release Notes: API/Release_Notes/API_Release_Notes.md
  - fa-file-text Download PDF /API/PDF/API_UG.pdf: API/PDF/index.md
- Data Portal:
  - Getting Started: Data_Portal/Users_Guide/Getting_Started.md
  - Projects: Data_Portal/Users_Guide/Projects.md
  - Cases And Files: Data_Portal/Users_Guide/Cases_and_Files.md
  - Annotations: Data_Portal/Users_Guide/Annotations.md
  - Advanced Search: Data_Portal/Users_Guide/Advanced_Search.md
  - Authentication: Data_Portal/Users_Guide/Authentication.md
  - File Cart: Data_Portal/Users_Guide/Cart.md
  - Legacy Archive: Data_Portal/Users_Guide/Legacy_Archive.md
  - Reports: Data_Portal/Users_Guide/Reports.md
  - Release Notes: Data_Portal/Release_Notes/Data_Portal_Release_Notes.md
  - GDC cBioPortal Release Notes: Data_Portal/Release_Notes/cBioPortal_Release_Notes.md
  - fa-file-text Download PDF /Data_Portal/PDF/Data_Portal_UG.pdf: Data_Portal/PDF/index.md
- Data Submission Portal:
  - Getting Started: Data_Submission_Portal/Users_Guide/Getting_Started.md
  - Submission Workflow: Data_Submission_Portal/Users_Guide/Submission_Workflow.md
  - Authentication: Data_Submission_Portal/Users_Guide/Authentication.md
  - Homepage: Data_Submission_Portal/Users_Guide/Homepage.md
  - Dashboard: Data_Submission_Portal/Users_Guide/Dashboard.md
  - Upload Data: Data_Submission_Portal/Users_Guide/Data_Upload_UG.md
  - Submit Data: Data_Submission_Portal/Users_Guide/Submit_Data.md
  - Release Data: Data_Submission_Portal/Users_Guide/Release_Data.md
  - Transactions: Data_Submission_Portal/Users_Guide/Transactions.md
  - Browse Data: Data_Submission_Portal/Users_Guide/Browse_Data.md
  - Release Notes: Data_Submission_Portal/Release_Notes/Data_Submission_Portal_Release_Notes.md
  - fa-file-text Download PDF /Data_Submission_Portal/PDF/Data_Submission_Portal_UG.pdf: Data_Submission_Portal/PDF/index.md
- Data Transfer Tool:
  - Getting Started: Data_Transfer_Tool/Users_Guide/Getting_Started.md
  - Accessing Built-in Help: Data_Transfer_Tool/Users_Guide/Accessing_Built-in_Help.md
  - Preparing for Data Download and Upload: Data_Transfer_Tool/Users_Guide/Preparing_for_Data_Download_and_Upload.md
  - Data Download and Upload: Data_Transfer_Tool/Users_Guide/Data_Download_and_Upload.md
  - Key Terms: Data_Transfer_Tool/Users_Guide/Appendix_A_-_Key_Terms.md
  - Release Notes: Data_Transfer_Tool/Release_Notes/DTT_Release_Notes.md
  - fa-file-text Download PDF /Data_Transfer_Tool/PDF/Data_Transfer_Tool_UG.pdf: Data_Transfer_Tool/PDF/index.md
- Data Dictionary:
  - About: Data_Dictionary/index.md
  - Viewer: Data_Dictionary/viewer.md
- Data:
  - Introduction: Data/Introduction.md
  - GDC Data Model: Data/Data_Model/GDC_Data_Model.md
  - Data Security: Data/Data_Security/Data_Security.md
  - 'File Format: MAF': Data/File_Formats/MAF_Format.md
  - 'File Format: VCF': Data/File_Formats/VCF_Format.md
  - 'Bioinformatics Pipeline: DNA-Seq Analysis': Data/Bioinformatics_Pipelines/DNA_Seq_Variant_Calling_Pipeline.md
  - 'Bioinformatics Pipeline: mRNA Analysis': Data/Bioinformatics_Pipelines/Expression_mRNA_Pipeline.md
  - 'Bioinformatics Pipeline: miRNA Analysis': Data/Bioinformatics_Pipelines/miRNA_Pipeline.md
  - 'Bioinformatics Pipeline: Copy Number Variation Analysis': Data/Bioinformatics_Pipelines/CNV_Pipeline.md
  - 'Bioinformatics Pipeline: Methylation Liftover Pipeline': Data/Bioinformatics_Pipelines/Methylation_LO_Pipeline.md
  - Release Notes: Data/Release_Notes/Data_Release_Notes.md
  - fa-file-text Download PDF /Data/PDF/Data_UG.pdf: Data/PDF/index.md
- Encyclopedia: Encyclopedia/index.md
- EncyclopediaEntries:
  - '42069': Encyclopedia/pages/42069.md
  - 56_notch: Encyclopedia/pages/56_notch.md
  - Affymetrix_SNP_6.0: Encyclopedia/pages/Affymetrix_SNP_6.0.md
  - Aggregated_Somatic_Mutation: Encyclopedia/pages/Aggregated_Somatic_Mutation.md
  - Aligned_Reads: Encyclopedia/pages/Aligned_Reads.md
  - Aliquot: Encyclopedia/pages/Aliquot.md
  - Analyte: Encyclopedia/pages/Analyte.md
  - Annotated_Somatic_Mutation: Encyclopedia/pages/Annotated_Somatic_Mutation.md
  - Annotation: Encyclopedia/pages/Annotation.md
  - BCGSC_miRNA_Profiling: Encyclopedia/pages/BCGSC_miRNA_Profiling.md
  - Binary_Alignment_Map: Encyclopedia/pages/Binary_Alignment_Map.md
  - Biospecimen_Core_Resource: Encyclopedia/pages/Biospecimen_Core_Resource.md
  - Biospecimen_Core_Resource_XML: Encyclopedia/pages/Biospecimen_Core_Resource_XML.md
  - Biospecimen_Data: Encyclopedia/pages/Biospecimen_Data.md
  - Biospecimen_Supplement: Encyclopedia/pages/Biospecimen_Supplement.md
  - BWA-aln: Encyclopedia/pages/BWA-aln.md
  - BWA_with_Mark_Duplicates_and_Cocleaning: Encyclopedia/pages/BWA_with_Mark_Duplicates_and_Cocleaning.md
  - Case: Encyclopedia/pages/Case.md
  - Center_for_Cancer_Genomics: Encyclopedia/pages/Center_for_Cancer_Genomics.md
  - Clinical_Data: Encyclopedia/pages/Clinical_Data.md
  - Clinical_Supplement: Encyclopedia/pages/Clinical_Supplement.md
  - Cocleaning_Workflow: Encyclopedia/pages/Cocleaning_Workflow.md
  - Controlled_Access: Encyclopedia/pages/Controlled_Access.md
  - Copy_Number_Segment: Encyclopedia/pages/Copy_Number_Segment.md
  - Copy_Number_Variation: Encyclopedia/pages/Copy_Number_Variation.md
  - Data Freeze: Encyclopedia/pages/Data Freeze.md
  - Data Integrity: Encyclopedia/pages/Data Integrity.md
  - Data Report: Encyclopedia/pages/Data Report.md
  - Data_Access_Policy: Encyclopedia/pages/Data_Access_Policy.md
  - Data_Archive: Encyclopedia/pages/Data_Archive.md
  - Data_Category_Template: Encyclopedia/pages/Data_Category_Template.md
  - Data_Format_Template: Encyclopedia/pages/Data_Format_Template.md
  - Data_Type_Template: Encyclopedia/pages/Data_Type_Template.md
  - DNA_Methylation: Encyclopedia/pages/DNA_Methylation.md
  - DNAcopy: Encyclopedia/pages/DNAcopy.md
  - Experimental_Strategy_Template: Encyclopedia/pages/Experimental_Strategy_Template.md
  - GDC_API: Encyclopedia/pages/GDC_API.md
  - GDC_cBioPortal: Encyclopedia/pages/GDC_cBioPortal.md
  - GDC_Data_Portal: Encyclopedia/pages/GDC_Data_Portal.md
  - GDC_Data_Submission_Portal: Encyclopedia/pages/GDC_Data_Submission_Portal.md
  - GDC_Data_Transfer_Tool: Encyclopedia/pages/GDC_Data_Transfer_Tool.md
  - GDC_Documentation_Site: Encyclopedia/pages/GDC_Documentation_Site.md
  - GDC_Web_Site: Encyclopedia/pages/GDC_Web_Site.md
  - Gene_Expression_Quantification: Encyclopedia/pages/Gene_Expression_Quantification.md
  - General_Template: Encyclopedia/pages/General_Template.md
  - Genomic_Data_Analysis_Network: Encyclopedia/pages/Genomic_Data_Analysis_Network.md
  - Genomic_Data_Commons: Encyclopedia/pages/Genomic_Data_Commons.md
  - Genotyping_Array: Encyclopedia/pages/Genotyping_Array.md
  - HTSeq-Counts: Encyclopedia/pages/HTSeq-Counts.md
  - HTSeq-FPKM-UQ: Encyclopedia/pages/HTSeq-FPKM-UQ.md
  - HTSeq-FPKM: Encyclopedia/pages/HTSeq-FPKM.md
  - Illumina: Encyclopedia/pages/Illumina.md
  - Illumina_Human_Methylation_27: Encyclopedia/pages/Illumina_Human_Methylation_27.md
  - Illumina_Human_Methylation_450: Encyclopedia/pages/Illumina_Human_Methylation_450.md
  - Isoform_Expression_Quantification: Encyclopedia/pages/Isoform_Expression_Quantification.md
  - Liftover: Encyclopedia/pages/Liftover.md
  - Masked_Copy_Number_Segment: Encyclopedia/pages/Masked_Copy_Number_Segment.md
  - Masked_Somatic_Mutation: Encyclopedia/pages/Masked_Somatic_Mutation.md
  - Methylation_Array: Encyclopedia/pages/Methylation_Array.md
  - Methylation_Beta_Value: Encyclopedia/pages/Methylation_Beta_Value.md
  - miRNA-Seq: Encyclopedia/pages/miRNA-Seq.md
  - miRNA_Expression_Quantification: Encyclopedia/pages/miRNA_Expression_Quantification.md
  - MuSE: Encyclopedia/pages/MuSE.md
  - MuSE_Annotation: Encyclopedia/pages/MuSE_Annotation.md
  - MuSE_Variant_Aggregation_and_Masking: Encyclopedia/pages/MuSE_Variant_Aggregation_and_Masking.md
  - Mutation: Encyclopedia/pages/Mutation.md
  - Mutation_Annotation_Format: Encyclopedia/pages/Mutation_Annotation_Format.md
  - MuTect2: Encyclopedia/pages/MuTect2.md
  - MuTect2_Annotation: Encyclopedia/pages/MuTect2_Annotation.md
  - MuTect2_Variant_Aggregation_and_Masking: Encyclopedia/pages/MuTect2_Variant_Aggregation_and_Masking.md
  - Open_Access: Encyclopedia/pages/Open_Access.md
  - Platform_Template: Encyclopedia/pages/Platform_Template.md
  - Portion: Encyclopedia/pages/Portion.md
  - Program: Encyclopedia/pages/Program.md
  - Project: Encyclopedia/pages/Project.md
  - Raw_Sequencing_Data: Encyclopedia/pages/Raw_Sequencing_Data.md
  - Raw_Simple_Somatic_Mutation: Encyclopedia/pages/Raw_Simple_Somatic_Mutation.md
  - Read_Group: Encyclopedia/pages/Read_Group.md
  - RNA-Seq: Encyclopedia/pages/RNA-Seq.md
  - Sample: Encyclopedia/pages/Sample.md
  - Simple_Nucleotide_Variation: Encyclopedia/pages/Simple_Nucleotide_Variation.md
  - Slide: Encyclopedia/pages/Slide.md
  - SomaticSniper: Encyclopedia/pages/SomaticSniper.md
  - SomaticSniper_Annotation: Encyclopedia/pages/SomaticSniper_Annotation.md
  - SomaticSniper_Variant_Aggregation_and_Masking: Encyclopedia/pages/SomaticSniper_Variant_Aggregation_and_Masking.md
  - STAR_2-Pass: Encyclopedia/pages/STAR_2-Pass.md
  - Tab_Separated_Values: Encyclopedia/pages/Tab_Separated_Values.md
  - Text_File: Encyclopedia/pages/Text_File.md
  - Tool_Template: Encyclopedia/pages/Tool_Template.md
  - Transcriptome_Profiling: Encyclopedia/pages/Transcriptome_Profiling.md
  - Variant_Aggregation_and_Masking: Encyclopedia/pages/Variant_Aggregation_and_Masking.md
  - Variant_Call_Annotation: Encyclopedia/pages/Variant_Call_Annotation.md
  - Variant_Call_Format: Encyclopedia/pages/Variant_Call_Format.md
  - VarScan2: Encyclopedia/pages/VarScan2.md
  - VarScan2_Annotation: Encyclopedia/pages/VarScan2_Annotation.md
  - VarScan2_Variant_Aggregation_and_Masking: Encyclopedia/pages/VarScan2_Variant_Aggregation_and_Masking.md
  - Whole_Exome_Sequencing: Encyclopedia/pages/Whole_Exome_Sequencing.md
  - Workflow_Type_Template: Encyclopedia/pages/Workflow_Type_Template.md
  - XLSX: Encyclopedia/pages/XLSX.md
repo_url: https://github.com/NCI-GDC/gdc-docs
site_name: GDC Docs
site_url: http://gdc-docs.nci.nih.gov
theme: mkdocs
theme_dir: theme
