#
# GDC Docs - Config
#

site_name: GDC Docs
site_url: http://gdc-docs.nci.nih.gov
repo_url: https://github.com/NCI-GDC/gdc-docs
copyright: "&copy; 2015-2016"
theme_dir: theme
pages:
- Home: 'index.md'
- API:
  - Getting Started: 'API/Users_Guide/Getting_Started.md'
  - Search and Retrieval: 'API/Users_Guide/Search_and_Retrieval.md'
  - Downloading Files: 'API/Users_Guide/Downloading_Files.md'
  - BAM Slicing: 'API/Users_Guide/BAM_Slicing.md'
  - Submission: 'API/Users_Guide/Submission.md'
  - System Information: 'API/Users_Guide/System_Information.md'
  - Additional Examples: 'API/Users_Guide/Additional_Examples.md'
  - "Appendix A: Available Fields": 'API/Users_Guide/Appendix_A_Available_Fields.md'
  - "Appendix B: Key Terms": 'API/Users_Guide/Appendix_B_Key_Terms.md'
  - "Appendix C: Format of Submission Queries and Responses": 'API/Users_Guide/Appendix_C_Format_of_Submission_Requests_and_Responses.md'
  - Release Notes: 'API/Release_Notes/API_Release_Notes.md'
  - fa-file-text Download PDF /API/PDF/API_UG.pdf: 'API/PDF/index.md'
- Data Portal:
  - Getting Started: 'Data_Portal/Users_Guide/Getting_Started.md'
  - Projects: 'Data_Portal/Users_Guide/Projects.md'
  - Cases And Files: 'Data_Portal/Users_Guide/Cases_and_Files.md'
  - Annotations: 'Data_Portal/Users_Guide/Annotations.md'
  - Advanced Search: 'Data_Portal/Users_Guide/Advanced_Search.md'
  - Authentication: 'Data_Portal/Users_Guide/Authentication.md'
  - File Cart: 'Data_Portal/Users_Guide/Cart.md'
  - Legacy Archive: 'Data_Portal/Users_Guide/Legacy_Archive.md'
  - Reports: 'Data_Portal/Users_Guide/Reports.md'
  - Release Notes: 'Data_Portal/Release_Notes/Data_Portal_Release_Notes.md'
  - GDC cBioPortal Release Notes: 'Data_Portal/Release_Notes/cBioPortal_Release_Notes.md'
  - fa-file-text Download PDF /Data_Portal/PDF/Data_Portal_UG.pdf: 'Data_Portal/PDF/index.md'
- Data Submission Portal:
  - Getting Started: 'Data_Submission_Portal/Users_Guide/Getting_Started.md'
  - Submission Workflow: 'Data_Submission_Portal/Users_Guide/Submission_Workflow.md'
  - Authentication: 'Data_Submission_Portal/Users_Guide/Authentication.md'
  - Homepage: 'Data_Submission_Portal/Users_Guide/Homepage.md'
  - Dashboard: 'Data_Submission_Portal/Users_Guide/Dashboard.md'
  - Upload Data: 'Data_Submission_Portal/Users_Guide/Data_Upload_UG.md'
  - Submit Data: 'Data_Submission_Portal/Users_Guide/Submit_Data.md'
  - Release Data: 'Data_Submission_Portal/Users_Guide/Release_Data.md'
  - Transactions: 'Data_Submission_Portal/Users_Guide/Transactions.md'
  - Browse Data: 'Data_Submission_Portal/Users_Guide/Browse_Data.md'
  - Release Notes: 'Data_Submission_Portal/Release_Notes/Data_Submission_Portal_Release_Notes.md'
  - fa-file-text Download PDF /Data_Submission_Portal/PDF/Data_Submission_Portal_UG.pdf: 'Data_Submission_Portal/PDF/index.md'
- Data Transfer Tool:
  - Getting Started: 'Data_Transfer_Tool/Users_Guide/Getting_Started.md'
  - Accessing Built-in Help: 'Data_Transfer_Tool/Users_Guide/Accessing_Built-in_Help.md'
  - Preparing for Data Download and Upload: 'Data_Transfer_Tool/Users_Guide/Preparing_for_Data_Download_and_Upload.md'
  - Data Download and Upload: 'Data_Transfer_Tool/Users_Guide/Data_Download_and_Upload.md'
  - Key Terms: 'Data_Transfer_Tool/Users_Guide/Appendix_A_-_Key_Terms.md'
  - Release Notes: 'Data_Transfer_Tool/Release_Notes/DTT_Release_Notes.md'
  - fa-file-text Download PDF /Data_Transfer_Tool/PDF/Data_Transfer_Tool_UG.pdf: 'Data_Transfer_Tool/PDF/index.md'
- Data Dictionary:
  - About: 'Data_Dictionary/index.md'
  - Viewer: 'Data_Dictionary/viewer.md'
- Data:
  - Introduction: 'Data/Introduction.md'
  - GDC Data Model: 'Data/Data_Model/GDC_Data_Model.md'
  - Data Security: 'Data/Data_Security/Data_Security.md'
  - "File Format: MAF": 'Data/File_Formats/MAF_Format.md'
  - "File Format: VCF": 'Data/File_Formats/VCF_Format.md'
  - "Bioinformatics Pipeline: DNA-Seq Analysis": 'Data/Bioinformatics_Pipelines/DNA_Seq_Variant_Calling_Pipeline.md'
  - "Bioinformatics Pipeline: mRNA Analysis": 'Data/Bioinformatics_Pipelines/Expression_mRNA_Pipeline.md'
  - "Bioinformatics Pipeline: miRNA Analysis": 'Data/Bioinformatics_Pipelines/miRNA_Pipeline.md'
  - "Bioinformatics Pipeline: Copy Number Variation Analysis": 'Data/Bioinformatics_Pipelines/CNV_Pipeline.md'
  - "Bioinformatics Pipeline: Methylation Liftover Pipeline": 'Data/Bioinformatics_Pipelines/Methylation_LO_Pipeline.md'
  - "Release Notes": 'Data/Release_Notes/Data_Release_Notes.md'
  - fa-file-text Download PDF /Data/PDF/Data_UG.pdf: 'Data/PDF/index.md'
- GDC Encyclopedia: 'Encyclopedia/index.md'
- EncyclopediaEntries:
  - Encyclopedia/Affymetrix_SNP_6.0.md
  - Encyclopedia/Aggregated_Somatic_Mutation.md
  - Encyclopedia/Aligned_Reads.md
  - Encyclopedia/Aliquot.md
  - Encyclopedia/Analyte.md
  - Encyclopedia/Annotated_Somatic_Mutation.md
  - Encyclopedia/Annotation.md
  - Encyclopedia/BCGSC_miRNA_Profiling.md
  - Encyclopedia/BWA-aln.md
  - Encyclopedia/BWA_with_Mark_Duplicates_and_Cocleaning.md
  - Encyclopedia/Binary_Alignment_Map.md
  - Encyclopedia/Biospecimen_Core_Resource.md
  - Encyclopedia/Biospecimen_Core_Resource_XML.md
  - Encyclopedia/Biospecimen_Data.md
  - Encyclopedia/Biospecimen_Supplement.md
  - Encyclopedia/Case.md
  - Encyclopedia/Center_for_Cancer_Genomics.md
  - Encyclopedia/Clinical_Data.md
  - Encyclopedia/Clinical_Supplement.md
  - Encyclopedia/Cocleaning_Workflow.md
  - Encyclopedia/Controlled_Access.md
  - Encyclopedia/Copy_Number_Segment.md
  - Encyclopedia/Copy_Number_Variation.md
  - Encyclopedia/DNA_Methylation.md
  - Encyclopedia/DNAcopy.md
  - Encyclopedia/Data Freeze.md
  - Encyclopedia/Data Integrity.md
  - Encyclopedia/Data Report.md
  - Encyclopedia/Data_Access_Policy.md
  - Encyclopedia/Data_Archive.md
  - Encyclopedia/Data_Category_Template.md
  - Encyclopedia/Data_Format_Template.md
  - Encyclopedia/Data_Type_Template.md
  - Encyclopedia/Experimental_Strategy_Template.md
  - Encyclopedia/GDC_API.md
  - Encyclopedia/GDC_Data_Portal.md
  - Encyclopedia/GDC_Data_Submission_Portal.md
  - Encyclopedia/GDC_Data_Transfer_Tool.md
  - Encyclopedia/GDC_Documentation_Site.md
  - Encyclopedia/GDC_Web_Site.md
  - Encyclopedia/GDC_cBioPortal.md
  - Encyclopedia/Gene_Expression_Quantification.md
  - Encyclopedia/General_Template.md
  - Encyclopedia/Genomic_Data_Analysis_Network.md
  - Encyclopedia/Genomic_Data_Commons.md
  - Encyclopedia/Genotyping_Array.md
  - Encyclopedia/HTSeq-Counts.md
  - Encyclopedia/HTSeq-FPKM-UQ.md
  - Encyclopedia/HTSeq-FPKM.md
  - Encyclopedia/Illumina.md
  - Encyclopedia/Illumina_Human_Methylation_27.md
  - Encyclopedia/Illumina_Human_Methylation_450.md
  - Encyclopedia/Isoform_Expression_Quantification.md
  - Encyclopedia/Liftover.md
  - Encyclopedia/Masked_Copy_Number_Segment.md
  - Encyclopedia/Masked_Somatic_Mutation.md
  - Encyclopedia/Methylation_Array.md
  - Encyclopedia/Methylation_Beta_Value.md
  - Encyclopedia/MuSE.md
  - Encyclopedia/MuSE_Annotation.md
  - Encyclopedia/MuSE_Variant_Aggregation_and_Masking.md
  - Encyclopedia/MuTect2.md
  - Encyclopedia/MuTect2_Annotation.md
  - Encyclopedia/MuTect2_Variant_Aggregation_and_Masking.md
  - Encyclopedia/Mutation.md
  - Encyclopedia/Mutation_Annotation_Format.md
  - Encyclopedia/Open_Access.md
  - Encyclopedia/Platform_Template.md
  - Encyclopedia/Portion.md
  - Encyclopedia/Program.md
  - Encyclopedia/Project.md
  - Encyclopedia/RNA-Seq.md
  - Encyclopedia/Raw_Sequencing_Data.md
  - Encyclopedia/Raw_Simple_Somatic_Mutation.md
  - Encyclopedia/Read_Group.md
  - Encyclopedia/STAR_2-Pass.md
  - Encyclopedia/Sample.md
  - Encyclopedia/Simple_Nucleotide_Variation.md
  - Encyclopedia/Slide.md
  - Encyclopedia/SomaticSniper.md
  - Encyclopedia/SomaticSniper_Annotation.md
  - Encyclopedia/SomaticSniper_Variant_Aggregation_and_Masking.md
  - Encyclopedia/Tab_Separated_Values.md
  - Encyclopedia/Text_File.md
  - Encyclopedia/Tool_Template.md
  - Encyclopedia/Transcriptome_Profiling.md
  - Encyclopedia/VarScan2.md
  - Encyclopedia/VarScan2_Annotation.md
  - Encyclopedia/VarScan2_Variant_Aggregation_and_Masking.md
  - Encyclopedia/Variant_Aggregation_and_Masking.md
  - Encyclopedia/Variant_Call_Annotation.md
  - Encyclopedia/Variant_Call_Format.md
  - Encyclopedia/Whole_Exome_Sequencing.md
  - Encyclopedia/Workflow_Type_Template.md
  - Encyclopedia/XLSX.md
  - Encyclopedia/miRNA-Seq.md
  - Encyclopedia/miRNA_Expression_Quantification.md
extra:
  project_root_dir: '/'
  project_org: 'GDC'
  project_description: 'GDC Docs'
  version: 1.0
  dictionary_viewer_page_id: 'Viewer'
  dictionary_app_root: '/apps/dictionary'
  encyclopedia_page_title: 'GDC Encyclopedia'
  encyclopedia_entries_page_title: 'EncyclopediaEntries'
  nav_exclude:
    - EncyclopediaEntries
extra_css:
  - css/encyclopedia.css
markdown_extensions:
  - tables
  - BSCodeTabExtension:
      default_lang: 'Source'
      show_all_code_as_folders: True
      animate_tab_transitions: False
theme: mkdocs
