#
# GDC Docs - Config
#

site_name: GDC Docs
site_url: http://gdc-docs.nci.nih.gov
repo_url: https://github.com/NCI-GDC/gdc-docs
copyright: "&copy; 2015-2016"
theme_dir: theme
pages:
- API:
  - Getting Started: 'API/Users_Guide/Getting_Started.md'
  - Authorization and Authentication: 'API/Users_Guide/Authentication_and_Authorization.md'
  - Search and Retrieval: 'API/Users_Guide/Search_and_Retrieval.md'
  - Downloading Files: 'API/Users_Guide/Downloading_Files.md'
  - BAM Slicing: 'API/Users_Guide/BAM_Slicing.md'
  - Submission: 'API/Users_Guide/Submission.md'
  - Additional Examples: 'API/Users_Guide/Additional_Examples.md'
  - "Appendix A: Available Fields": 'API/Users_Guide/Appendix_A_Available_Fields.md'
  - "Appendix B: Key Terms": 'API/Users_Guide/Appendix_B_Key_Terms.md'
  - "Appendix C: Format of Submission Queries and Responses": 'API/Users_Guide/Appendix_C_Format_of_Submission_Requests_and_Responses.md'
- Data Portal:
  - Getting Started: 'Data_Portal/Users_Guide/Getting_Started.md'
  - About the Data: 'Commons/About_the_Data.md'
  - Authentication: 'Commons/Authentication.md'
  - Features: 'Data_Portal/Users_Guide/Features.md'
  - Projects: 'Data_Portal/Users_Guide/Projects.md'
  - Data: 'Data_Portal/Users_Guide/Data.md'
  - BAM Slicing: 'Data_Portal/Users_Guide/BAM_Slicing.md'
  - Annotations: 'Data_Portal/Users_Guide/Annotations.md'
  - Advanced Search: 'Data_Portal/Users_Guide/Advanced_Search.md'
  - Reports: 'Data_Portal/Users_Guide/Reports.md'
  - Cart and Files Download: 'Data_Portal/Users_Guide/Cart.md'
  - Legacy Archive: 'Data_Portal/Users_Guide/Legacy_Archive.md'
  - Key Terms: 'Data_Portal/Users_Guide/Key_Terms.md'
- Data Submission Portal:
  - Getting Started: 'Data_Submission_Portal/Users_Guide/Getting_Started.md'
  - Submission Workflow: 'Data_Submission_Portal/Users_Guide/Submission_Workflow.md'
  - Authentication: 'Commons/Authentication.md'
  - Features: 'Data_Submission_Portal/Users_Guide/Features.md'
  - User Access: 'Data_Submission_Portal/Users_Guide/Login.md'
  - Homepage: 'Data_Submission_Portal/Users_Guide/Homepage.md'
  - Dashboard: 'Data_Submission_Portal/Users_Guide/Dashboard.md'
  - Upload and Validate Data: 'Data_Submission_Portal/Users_Guide/Upload_Data.md'
  - Submit and Release Data: 'Data_Submission_Portal/Users_Guide/Submit_Release.md'
  - Browse Data: 'Data_Submission_Portal/Users_Guide/Browse_Data.md'
  - Reports: 'Data_Submission_Portal/Users_Guide/Reports.md'
  - Transactions: 'Data_Submission_Portal/Users_Guide/Transactions.md'
- Data Transfer Tool:
  - Getting Started: 'Data_Transfer_Tool/Users_Guide/Getting_Started.md'
  - Accessing Built-in Help: 'Data_Transfer_Tool/Users_Guide/Accessing_Built-in_Help.md'
  - Preparing for Data Download and Upload: 'Data_Transfer_Tool/Users_Guide/Preparing_for_Data_Download_and_Upload.md'
  - Data Download and Upload: 'Data_Transfer_Tool/Users_Guide/Data_Download_and_Upload.md'
  - Key Terms: 'Data_Transfer_Tool/Users_Guide/Appendix_A_-_Key_Terms.md'
- Data Dictionary:
  - About: 'Data_Dictionary/index.md'
  - Viewer: 'Data_Dictionary/viewer.md'
- Releases:
  - API Release Notes: 'Releases/API/API_Release_Notes.md'
  - Data Release Notes: 'Releases/Data/Data_Release_Notes.md'
  - Portal Release Notes: 'Releases/Data_Portal/Data_Portal_Release_Notes.md'
  - Submission Portal Release Notes: 'Releases/Submission_Portal/Data_Submission_Portal_Release_Notes.md'
  - Transfer Tool Release Notes: 'Releases/Data_Transfer_Tool/GDC_Data_Transfer_Tool_Release_Notes.md'
extra:
  project_root_dir: '/'
  project_org: 'GDC'
  project_description: 'GDC Docs'
  version: 1.0
  dictionary_viewer_page_id: 'Viewer'
  dictionary_app_root: '/apps/dictionary'
markdown_extensions:
  - BSCodeTabExtension:
      default_lang: 'Source'
      show_all_code_as_folders: True
      animate_tab_transitions: False
