#
# GDC Docs - Config
#

site_name: GDC Docs
site_url: http://gdc-docs.nci.nih.gov
repo_url: https://github.com/NCI-GDC/gdc-docs
copyright: "&copy; 2015-2016"
theme_dir: theme
pages:
- Home: 'index.md'
- Data Portal:
  - About: 'Data_Portal/Users_Guide/01-Using_the_GDC_Data_Portal_User_Guide.md'
  - About the Data: 'Commons/About_the_Data.md'
  - Getting Started: 'Data_Portal/Users_Guide/02-Getting_Started_with_the_GDC_Data_Portal.md'
  - Authentication: 'Commons/Authentication.md'
  - Overview and Features: 'Data_Portal/Users_Guide/03-Overview_and_Features.md'
  - Projects: 'Data_Portal/Users_Guide/04-Projects.md'
  - Cases and Files: 'Data_Portal/Users_Guide/05-Cases_and_files.md'
  - BAM Slicing: 'Data_Portal/Users_Guide/06-BAM_Slicing.md'
  - Annotations: 'Data_Portal/Users_Guide/07-Annotations.md'
  - Advanced Search: 'Data_Portal/Users_Guide/08-Advanced_Search.md'
  - Reports: 'Data_Portal/Users_Guide/09-Reports.md'
  - Cart and Files Download: 'Data_Portal/Users_Guide/10-Cart_and_Files_download.md'
  - Release Notes:
     - 0.2.18.3: 'Data_Portal/Release_Notes/0.2.18.3.md'
     - 0.2.15.4: 'Data_Portal/Release_Notes/0.2.15.4.md'
     - 0.2.15.2: 'Data_Portal/Release_Notes/0.2.15.2.md'
     - 0.2.15.1: 'Data_Portal/Release_Notes/0.2.15.1.md'
     - 0.2.13: 'Data_Portal/Release_Notes/0.2.13.md'
     - 0.1.10: 'Data_Portal/Release_Notes/0.1.10.md'
     - 0.1.8: 'Data_Portal/Release_Notes/0.1.8.md'
- Submission Portal:
  - About: 'index.md'
  - Guide: 'index.md'
- API:
  - About: 'index.md'
  - Guide: 'index.md'
- Transfer Tool:
  - About: 'index.md'
  - Guide: 'index.md'
extra:
  project_root_dir: '/'
  project_org: 'GDC'
  project_description: 'GDC Docs'
  version: 1.0
