#
# GDC Docs - Config
#

site_name: GDC Docs
site_url: http://gdc-docs.nci.nih.gov
repo_url: https://github.com/NCI-GDC/gdc-docs
copyright: "&copy; 2015-2016"
theme_dir: theme
pages:
- Home: 'index.md'
- API:
  - Getting Started: 'API/Users_Guide/Getting_Started.md'
  - Search and Retrieval: 'API/Users_Guide/Search_and_Retrieval.md'
  - Downloading Files: 'API/Users_Guide/Downloading_Files.md'
  - BAM Slicing: 'API/Users_Guide/BAM_Slicing.md'
  - Submission: 'API/Users_Guide/Submission.md'
  - System Information: 'API/Users_Guide/System_Information.md'
  - Additional Examples: 'API/Users_Guide/Additional_Examples.md'
  - "Appendix A: Available Fields": 'API/Users_Guide/Appendix_A_Available_Fields.md'
  - "Appendix B: Key Terms": 'API/Users_Guide/Appendix_B_Key_Terms.md'
  - "Appendix C: Format of Submission Queries and Responses": 'API/Users_Guide/Appendix_C_Format_of_Submission_Requests_and_Responses.md'
  - Release Notes: 'API/Release_Notes/API_Release_Notes.md'
  - fa-file-text Download PDF /API/PDF/API_UG.pdf: 'API/PDF/index.md'
- Data Portal:
  - Getting Started: 'Data_Portal/Users_Guide/Getting_Started.md'
  - Projects: 'Data_Portal/Users_Guide/Projects.md'
  - Cases And Files: 'Data_Portal/Users_Guide/Cases_and_Files.md'
  - Annotations: 'Data_Portal/Users_Guide/Annotations.md'
  - Advanced Search: 'Data_Portal/Users_Guide/Advanced_Search.md'
  - Authentication: 'Data_Portal/Users_Guide/Authentication.md'
  - File Cart: 'Data_Portal/Users_Guide/Cart.md'
  - Legacy Archive: 'Data_Portal/Users_Guide/Legacy_Archive.md'
  - Reports: 'Data_Portal/Users_Guide/Reports.md'
  - Release Notes: 'Data_Portal/Release_Notes/Data_Portal_Release_Notes.md'
  - GDC cBioPortal Release Notes: 'Data_Portal/Release_Notes/cBioPortal_Release_Notes.md'
  - fa-file-text Download PDF /Data_Portal/PDF/Data_Portal_UG.pdf: 'Data_Portal/PDF/index.md'
- Data Submission Portal:
  - Getting Started: 'Data_Submission_Portal/Users_Guide/Getting_Started.md'
  - Submission Workflow: 'Data_Submission_Portal/Users_Guide/Submission_Workflow.md'
  - Authentication: 'Data_Submission_Portal/Users_Guide/Authentication.md'
  - Homepage: 'Data_Submission_Portal/Users_Guide/Homepage.md'
  - Dashboard: 'Data_Submission_Portal/Users_Guide/Dashboard.md'
  - Upload Data: 'Data_Submission_Portal/Users_Guide/Data_Upload_UG.md'
  - Submit Data: 'Data_Submission_Portal/Users_Guide/Submit_Data.md'
  - Release Data: 'Data_Submission_Portal/Users_Guide/Release_Data.md'
  - Transactions: 'Data_Submission_Portal/Users_Guide/Transactions.md'
  - Browse Data: 'Data_Submission_Portal/Users_Guide/Browse_Data.md'
  - Release Notes: 'Data_Submission_Portal/Release_Notes/Data_Submission_Portal_Release_Notes.md'
  - fa-file-text Download PDF /Data_Submission_Portal/PDF/Data_Submission_Portal_UG.pdf: 'Data_Submission_Portal/PDF/index.md'
- Data Transfer Tool:
  - Getting Started: 'Data_Transfer_Tool/Users_Guide/Getting_Started.md'
  - Accessing Built-in Help: 'Data_Transfer_Tool/Users_Guide/Accessing_Built-in_Help.md'
  - Preparing for Data Download and Upload: 'Data_Transfer_Tool/Users_Guide/Preparing_for_Data_Download_and_Upload.md'
  - Data Download and Upload: 'Data_Transfer_Tool/Users_Guide/Data_Download_and_Upload.md'
  - Key Terms: 'Data_Transfer_Tool/Users_Guide/Appendix_A_-_Key_Terms.md'
  - Release Notes: 'Data_Transfer_Tool/Release_Notes/DTT_Release_Notes.md'
  - fa-file-text Download PDF /Data_Transfer_Tool/PDF/Data_Transfer_Tool_UG.pdf: 'Data_Transfer_Tool/PDF/index.md'
- Data Dictionary:
  - About: 'Data_Dictionary/index.md'
  - Viewer: 'Data_Dictionary/viewer.md'
- Data:
  - Introduction: 'Data/Introduction.md'
  - GDC Data Model: 'Data/Data_Model/GDC_Data_Model.md'
  - Data Security: 'Data/Data_Security/Data_Security.md'
  - "File Format: MAF": 'Data/File_Formats/MAF_Format.md'
  - "File Format: VCF": 'Data/File_Formats/VCF_Format.md'
  - "Bioinformatics Pipeline: DNA-Seq Analysis": 'Data/Bioinformatics_Pipelines/DNA_Seq_Variant_Calling_Pipeline.md'
  - "Bioinformatics Pipeline: mRNA Analysis": 'Data/Bioinformatics_Pipelines/Expression_mRNA_Pipeline.md'
  - "Bioinformatics Pipeline: miRNA Analysis": 'Data/Bioinformatics_Pipelines/miRNA_Pipeline.md'
  - "Bioinformatics Pipeline: Copy Number Variation Analysis": 'Data/Bioinformatics_Pipelines/CNV_Pipeline.md'
  - "Bioinformatics Pipeline: Methylation Liftover Pipeline": 'Data/Bioinformatics_Pipelines/Methylation_LO_Pipeline.md'
  - "Release Notes": 'Data/Release_Notes/Data_Release_Notes.md'
  - fa-file-text Download PDF /Data/PDF/Data_UG.pdf: 'Data/PDF/index.md'
- GDC Encyclopedia: 'Encyclopedia/index.md'
- EncyclopediaEntries:
  - Affymetrix_SNP_6.0: Encyclopedia/Affymetrix_SNP_6.0.md
  - Aggregated_Somatic_Mutation: Encyclopedia/Aggregated_Somatic_Mutation.md
  - Aligned_Reads: Encyclopedia/Aligned_Reads.md
  - Aliquot: Encyclopedia/Aliquot.md
  - Analyte: Encyclopedia/Analyte.md
  - Annotated_Somatic_Mutation: Encyclopedia/Annotated_Somatic_Mutation.md
  - Annotation: Encyclopedia/Annotation.md
  - BCGSC_miRNA_Profiling: Encyclopedia/BCGSC_miRNA_Profiling.md
  - BWA-aln: Encyclopedia/BWA-aln.md
  - BWA_with_Mark_Duplicates_and_Cocleaning: Encyclopedia/BWA_with_Mark_Duplicates_and_Cocleaning.md
  - Binary_Alignment_Map: Encyclopedia/Binary_Alignment_Map.md
  - Biospecimen_Core_Resource: Encyclopedia/Biospecimen_Core_Resource.md
  - Biospecimen_Core_Resource_XML: Encyclopedia/Biospecimen_Core_Resource_XML.md
  - Biospecimen_Data: Encyclopedia/Biospecimen_Data.md
  - Biospecimen_Supplement: Encyclopedia/Biospecimen_Supplement.md
  - Case: Encyclopedia/Case.md
  - Center_for_Cancer_Genomics: Encyclopedia/Center_for_Cancer_Genomics.md
  - Clinical_Data: Encyclopedia/Clinical_Data.md
  - Clinical_Supplement: Encyclopedia/Clinical_Supplement.md
  - Cocleaning_Workflow: Encyclopedia/Cocleaning_Workflow.md
  - Controlled_Access: Encyclopedia/Controlled_Access.md
  - Copy_Number_Segment: Encyclopedia/Copy_Number_Segment.md
  - Copy_Number_Variation: Encyclopedia/Copy_Number_Variation.md
  - DNA_Methylation: Encyclopedia/DNA_Methylation.md
  - DNAcopy: Encyclopedia/DNAcopy.md
  - Data Freeze: Encyclopedia/Data Freeze.md
  - Data Integrity: Encyclopedia/Data Integrity.md
  - Data Report: Encyclopedia/Data Report.md
  - Data_Access_Policy: Encyclopedia/Data_Access_Policy.md
  - Data_Archive: Encyclopedia/Data_Archive.md
  - Data_Category_Template: Encyclopedia/Data_Category_Template.md
  - Data_Format_Template: Encyclopedia/Data_Format_Template.md
  - Data_Type_Template: Encyclopedia/Data_Type_Template.md
  - Experimental_Strategy_Template: Encyclopedia/Experimental_Strategy_Template.md
  - GDC_API: Encyclopedia/GDC_API.md
  - GDC_Data_Portal: Encyclopedia/GDC_Data_Portal.md
  - GDC_Data_Submission_Portal: Encyclopedia/GDC_Data_Submission_Portal.md
  - GDC_Data_Transfer_Tool: Encyclopedia/GDC_Data_Transfer_Tool.md
  - GDC_Documentation_Site: Encyclopedia/GDC_Documentation_Site.md
  - GDC_Web_Site: Encyclopedia/GDC_Web_Site.md
  - GDC_cBioPortal: Encyclopedia/GDC_cBioPortal.md
  - Gene_Expression_Quantification: Encyclopedia/Gene_Expression_Quantification.md
  - General_Template: Encyclopedia/General_Template.md
  - Genomic_Data_Analysis_Network: Encyclopedia/Genomic_Data_Analysis_Network.md
  - Genomic_Data_Commons: Encyclopedia/Genomic_Data_Commons.md
  - Genotyping_Array: Encyclopedia/Genotyping_Array.md
  - HTSeq-Counts: Encyclopedia/HTSeq-Counts.md
  - HTSeq-FPKM-UQ: Encyclopedia/HTSeq-FPKM-UQ.md
  - HTSeq-FPKM: Encyclopedia/HTSeq-FPKM.md
  - Illumina: Encyclopedia/Illumina.md
  - Illumina_Human_Methylation_27: Encyclopedia/Illumina_Human_Methylation_27.md
  - Illumina_Human_Methylation_450: Encyclopedia/Illumina_Human_Methylation_450.md
  - Isoform_Expression_Quantification: Encyclopedia/Isoform_Expression_Quantification.md
  - Liftover: Encyclopedia/Liftover.md
  - Masked_Copy_Number_Segment: Encyclopedia/Masked_Copy_Number_Segment.md
  - Masked_Somatic_Mutation: Encyclopedia/Masked_Somatic_Mutation.md
  - Methylation_Array: Encyclopedia/Methylation_Array.md
  - Methylation_Beta_Value: Encyclopedia/Methylation_Beta_Value.md
  - MuSE: Encyclopedia/MuSE.md
  - MuSE_Annotation: Encyclopedia/MuSE_Annotation.md
  - MuSE_Variant_Aggregation_and_Masking: Encyclopedia/MuSE_Variant_Aggregation_and_Masking.md
  - MuTect2: Encyclopedia/MuTect2.md
  - MuTect2_Annotation: Encyclopedia/MuTect2_Annotation.md
  - MuTect2_Variant_Aggregation_and_Masking: Encyclopedia/MuTect2_Variant_Aggregation_and_Masking.md
  - Mutation: Encyclopedia/Mutation.md
  - Mutation_Annotation_Format: Encyclopedia/Mutation_Annotation_Format.md
  - Open_Access: Encyclopedia/Open_Access.md
  - Platform_Template: Encyclopedia/Platform_Template.md
  - Portion: Encyclopedia/Portion.md
  - Program: Encyclopedia/Program.md
  - Project: Encyclopedia/Project.md
  - RNA-Seq: Encyclopedia/RNA-Seq.md
  - Raw_Sequencing_Data: Encyclopedia/Raw_Sequencing_Data.md
  - Raw_Simple_Somatic_Mutation: Encyclopedia/Raw_Simple_Somatic_Mutation.md
  - Read_Group: Encyclopedia/Read_Group.md
  - STAR_2-Pass: Encyclopedia/STAR_2-Pass.md
  - Sample: Encyclopedia/Sample.md
  - Simple_Nucleotide_Variation: Encyclopedia/Simple_Nucleotide_Variation.md
  - Slide: Encyclopedia/Slide.md
  - SomaticSniper: Encyclopedia/SomaticSniper.md
  - SomaticSniper_Annotation: Encyclopedia/SomaticSniper_Annotation.md
  - SomaticSniper_Variant_Aggregation_and_Masking: Encyclopedia/SomaticSniper_Variant_Aggregation_and_Masking.md
  - Tab_Separated_Values: Encyclopedia/Tab_Separated_Values.md
  - Text_File: Encyclopedia/Text_File.md
  - Tool_Template: Encyclopedia/Tool_Template.md
  - Transcriptome_Profiling: Encyclopedia/Transcriptome_Profiling.md
  - VarScan2: Encyclopedia/VarScan2.md
  - VarScan2_Annotation: Encyclopedia/VarScan2_Annotation.md
  - VarScan2_Variant_Aggregation_and_Masking: Encyclopedia/VarScan2_Variant_Aggregation_and_Masking.md
  - Variant_Aggregation_and_Masking: Encyclopedia/Variant_Aggregation_and_Masking.md
  - Variant_Call_Annotation: Encyclopedia/Variant_Call_Annotation.md
  - Variant_Call_Format: Encyclopedia/Variant_Call_Format.md
  - Whole_Exome_Sequencing: Encyclopedia/Whole_Exome_Sequencing.md
  - Workflow_Type_Template: Encyclopedia/Workflow_Type_Template.md
  - XLSX: Encyclopedia/XLSX.md
  - miRNA-Seq: Encyclopedia/miRNA-Seq.md
  - miRNA_Expression_Quantification: Encyclopedia/miRNA_Expression_Quantification.md
extra:
  project_root_dir: '/'
  project_org: 'GDC'
  project_description: 'GDC Docs'
  version: 1.0
  dictionary_viewer_page_id: 'Viewer'
  dictionary_app_root: '/apps/dictionary'
  encyclopedia_page_title: 'GDC Encyclopedia'
  encyclopedia_entries_page_title: 'EncyclopediaEntries'
  nav_exclude:
    - EncyclopediaEntries
extra_css:
  - css/encyclopedia.css
markdown_extensions:
  - tables
  - BSCodeTabExtension:
      default_lang: 'Source'
      show_all_code_as_folders: True
      animate_tab_transitions: False
theme: mkdocs
