#
# GDC Docs - Config
#

site_name: GDC Docs
site_url: http://gdc-docs.nci.nih.gov
repo_url: https://github.com/NCI-GDC/gdc-docs
copyright: "&copy; 2015-2016"
theme_dir: theme
pages:
- API:
  - About: 'index.md'
  - Guide: 'index.md'
- Data Portal:
  - Getting Started: 'Data_Portal/Users_Guide/Getting_Started.md'
  - About the Data: 'Commons/About_the_Data.md'
  - Authentication: 'Commons/Authentication.md'
  - Portal Features: 'Data_Portal/Users_Guide/Features.md'
  - Projects: 'Data_Portal/Users_Guide/Projects.md'
  - Cases and Files: 'Data_Portal/Users_Guide/Data.md'
  - BAM Slicing: 'Data_Portal/Users_Guide/BAM_Slicing.md'
  - Annotations: 'Data_Portal/Users_Guide/Annotations.md'
  - Advanced Search: 'Data_Portal/Users_Guide/Advanced_Search.md'
  - Reports: 'Data_Portal/Users_Guide/Reports.md'
  - Cart and Files Download: 'Data_Portal/Users_Guide/Cart.md'
  - Key Terms: 'Data_Portal/Users_Guide/Key_Terms.md'
  - Release Notes:
     - 0.2.18.3: 'Data_Portal/Release_Notes/0.2.18.3.md'
     - 0.2.15.4: 'Data_Portal/Release_Notes/0.2.15.4.md'
     - 0.2.15.2: 'Data_Portal/Release_Notes/0.2.15.2.md'
     - 0.2.15.1: 'Data_Portal/Release_Notes/0.2.15.1.md'
     - 0.2.13: 'Data_Portal/Release_Notes/0.2.13.md'
     - 0.1.10: 'Data_Portal/Release_Notes/0.1.10.md'
     - 0.1.8: 'Data_Portal/Release_Notes/0.1.8.md'
- Submission Portal:
  - Getting Started: 'Data_Submission_Portal/Users_Guide/Getting_Started.md'
  - Authentication: 'Commons/Authentication.md'
  - Overview and Features: 'Data_Submission_Portal/Users_Guide/Features.md'
  - User Access: 'Data_Submission_Portal/Users_Guide/Login.md'
  - Landing Page: 'Data_Submission_Portal/Users_Guide/Landing_Page.md'
  - Dashboard: 'Data_Submission_Portal/Users_Guide/Dashboard.md'
  - Dictionary Viewer: 'Data_Submission_Portal/Users_Guide/Dictionary_Viewer.md'
  - Submit Data: 'Data_Submission_Portal/Users_Guide/Submit_Data.md'
  - Cases: 'Data_Submission_Portal/Users_Guide/Cases.md'
  - Biospecimen: 'Data_Submission_Portal/Users_Guide/Biospecimen.md'
  - Data: 'Data_Submission_Portal/Users_Guide/Data.md'
  - Reports: 'Data_Submission_Portal/Users_Guide/Reports.md'
  - Transactions: 'Data_Submission_Portal/Users_Guide/Transactions.md'
  - Release Notes:
     - 0.3.21: 'Data_Submission_Portal/Release_Notes/0.3.21.md'
     - 0.2.18.3: 'Data_Submission_Portal/Release_Notes/0.2.18.3.md'
- Transfer Tool:
  - About: 'index.md'
  - Guide: 'index.md'
- Dictionary:
  - About: 'index.md'
extra:
  project_root_dir: '/'
  project_org: 'GDC'
  project_description: 'GDC Docs'
  version: 1.0
